sonar.projectKey=angular-project
sonar.projectName=Angular Project
sonar.projectVersion=1.0

# Directorio raíz del código
sonar.sources=src

# Ignorar archivos que no necesitas analizar
sonar.exclusions=**/*.spec.ts,**/node_modules/**

# Lenguaje
sonar.language=ts

# Clave del token si estás autenticando
# sonar.login=your_token

# Tipo de codificación
sonar.sourceEncoding=UTF-8
